#los yml son arbolados 
#   spring:
#     aop:
#       auto: true
#       proxy-target-class: false
#     messages:
#       always-use-message-format: false
#       basename: messages
#       cache-seconds: -1
#     mvc:
#       dispatch-trace-request: false
#       dispatch-options-request: true
      
#     couchbase:
#       bucket:
#         name: default
#   security:
#     oauth2:
#       resource:
#         prefer-token-info: true 
#         service-id: resource
      
banner:
  location: classpath:/javo/banner.txt
